name: CI
on:
  push:
    branches: [goshujin-sama]
  pull_request:
    branches: [goshujin-sama]
jobs:
  rust_test:
    name: Rust test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      # - run: cargo test --all-features
      - run: cargo fmt --check
      - run: cargo clippy --all-features -- --no-deps -Dwarnings
  js_test:
    name: JS test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install wasm-pack
        run: |
          version="$(cut -d ' ' -f 2 wasm-pack-version.txt)"
          dir="wasm-pack-v$version-x86_64-unknown-linux-musl"
          curl -sSfL -o "$RUNNER_TEMP/wasm-pack.tar.gz" "https://github.com/wasm-bindgen/wasm-pack/releases/download/v$version/$dir.tar.gz"
          tar xzf "$RUNNER_TEMP/wasm-pack.tar.gz" -C "$RUNNER_TEMP"
          echo "$RUNNER_TEMP/$dir" >> "$GITHUB_PATH"
      - run: pnpm install
      - run: pnpm run format:check
      - run: pnpm run build
      - run: pnpm run test
