on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: npm run build
      - run: npm run pretest
      - run: npm test
